# Generated by Django 2.1.7 on 2019-03-27 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github', models.CharField(max_length=150)),
                ('firstName', models.CharField(blank=True, default='John', max_length=150)),
                ('lastName', models.CharField(blank=True, default='Smith', max_length=150)),
                ('email', models.CharField(blank=True, default='no@email.com', max_length=150)),
                ('displayName', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True, default='No bio')),
                ('host', models.URLField(blank=True, default='http://127.0.0.1:8000')),
                ('image', models.URLField(blank=True, default='http://127.0.0.1:8000/static/socialapp/question-mark-face.jpg')),
                ('feed', models.URLField(blank=True)),
                ('isVerified', models.BooleanField(default=True)),
                ('friend_requests', models.ManyToManyField(blank=True, related_name='sent_friend_requests', to='socialapp.Author')),
                ('friends', models.ManyToManyField(blank=True, related_name='friend_by', to='socialapp.Author')),
                ('localuser', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['displayName'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('contentType', models.CharField(choices=[('text/markdown', 'Markdown')], default='text/markdown', max_length=64)),
                ('published', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_by', to='socialapp.Author')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('friendlyName', models.CharField(max_length=150)),
                ('endpoint', models.URLField()),
                ('password', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['friendlyName'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correlationId', models.IntegerField(blank=True, default=-1, editable=False)),
                ('title', models.CharField(max_length=150)),
                ('source', models.URLField()),
                ('origin', models.URLField()),
                ('description', models.CharField(max_length=280)),
                ('contentType', models.CharField(choices=[('text/plain', 'Plain'), ('application/base64', 'File'), ('image/png;base64', 'PNG'), ('text/markdown', 'Markdown'), ('image/jpeg;base64', 'JPEG')], default='text/markdown', max_length=64)),
                ('content', models.TextField()),
                ('categories', models.CharField(blank=True, default='', max_length=280)),
                ('published', models.DateTimeField()),
                ('visibility', models.CharField(choices=[('FRIENDS', 'Private to Friends'), ('PUBLIC', 'Public'), ('FOAF', 'Private to Friends of Friends'), ('SERVERONLY', 'Public To This Host'), ('PRIVATE', 'Private To Me (And Selected People)')], default='PUBLIC', max_length=64)),
                ('unlisted', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_by', to='socialapp.Author')),
                ('visibleTo', models.ManyToManyField(blank=True, related_name='visibleTo', to='socialapp.Author')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='socialapp.Post'),
        ),
    ]
