# Generated by Django 2.1.7 on 2019-03-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='feed',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(blank=True),
        ),
    ]
