# Generated by Django 2.1.7 on 2019-03-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/markdown', 'Markdown'), ('text/plain', 'Plain'), ('image/jpeg;base64', 'JPEG'), ('application/base64', 'File'), ('image/png;base64', 'PNG')], default='text/markdown', max_length=64),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'Private To Me (And Selected People)'), ('PUBLIC', 'Public'), ('FOAF', 'Private to Friends of Friends'), ('SERVERONLY', 'Public To This Host'), ('FRIENDS', 'Private to Friends')], default='PUBLIC', max_length=64),
        ),
    ]
