# Generated by Django 2.1.7 on 2019-03-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_auto_20190327_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/plain', 'Plain'), ('image/png;base64', 'PNG'), ('application/base64', 'File'), ('image/jpeg;base64', 'JPEG'), ('text/markdown', 'Markdown')], default='text/markdown', max_length=64),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('FRIENDS', 'Private to Friends'), ('PRIVATE', 'Private To Me (And Selected People)'), ('FOAF', 'Private to Friends of Friends'), ('PUBLIC', 'Public'), ('SERVERONLY', 'Public To This Host')], default='PUBLIC', max_length=64),
        ),
    ]
