# Generated by Django 2.1.7 on 2019-03-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0003_auto_20190327_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('application/base64', 'File'), ('text/markdown', 'Markdown'), ('image/jpeg;base64', 'JPEG'), ('image/png;base64', 'PNG'), ('text/plain', 'Plain')], default='text/markdown', max_length=64),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private To Me (And Selected People)'), ('FOAF', 'Private to Friends of Friends'), ('SERVERONLY', 'Public To This Host'), ('FRIENDS', 'Private to Friends')], default='PUBLIC', max_length=64),
        ),
    ]
