# Generated by Django 2.1.7 on 2019-03-11 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0003_auto_20190311_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibleTo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='visibleTo', to='socialapp.Author'),
        ),
    ]
