# Generated by Django 2.1.7 on 2019-03-11 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0004_auto_20190311_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialapp.PostTags'),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibleTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visibleTo', to='socialapp.Author'),
        ),
    ]
