# Generated by Django 2.1.7 on 2019-03-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0004_auto_20190327_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('application/base64', 'File'), ('image/png;base64', 'PNG'), ('text/markdown', 'Markdown'), ('image/jpeg;base64', 'JPEG'), ('text/plain', 'Plain')], default='text/markdown', max_length=64),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('FOAF', 'Private to Friends of Friends'), ('PUBLIC', 'Public'), ('FRIENDS', 'Private to Friends'), ('PRIVATE', 'Private To Me (And Selected People)'), ('SERVERONLY', 'Public To This Host')], default='PUBLIC', max_length=64),
        ),
    ]
